# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: BorbosCI

on:
  push:
    branches: 
    - main_develop
    - main_test
  pull_request:
    branches:
    - main_develop
    - main_test
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Step 3 - Build with Maven
      run: mvn -B package --file SistemaBorbosBlock/pom.xml
    - name: Test with Maven
      run: mvn test --file SistemaBorbosBlock/pom.xml
    #- name: Surefire Report
    #  uses: ScaCap/action-surefire-report@v1.0.5 
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
       files: "target/**/*.xml"
